app:
  env: dev
  data_dir: data
  log_level: INFO

data_provider:
  name: yahoo
  cache: false

broker:
  name: paper
  api_key: "YOUR_API_KEY"
  api_secret: "YOUR_API_SECRET"

strategy:
  name: BuyAndHold
  parameters: {}

